spring.application.name=aluguelcarros_vrs1

spring.datasource.url=jdbc:postgresql://localhost:5432/aluguelcarros
spring.datasource.username=postgres
spring.datasource.password=positivo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

api.security.token.secret=${JWT_SECRET:12345}
api.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

spring.web.locale-resolver=accept-header
spring.web.locale=pt_BR
server.error.include-stacktrace = never



