spring.application.name=aluguelcarros_vrs1

spring.profiles.active=production

# Localizacao e Erros
spring.web.locale=pt_BR
spring.web.locale-resolver=accept-header
server.error.include-stacktrace = never

# Jackson (Datas)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

spring.flyway.locations=classpath:db/migration




