### Cadastrar Aluguel
POST http://localhost:8080/aluguel/cadastrar
Content-Type: application/json

{
    "dias_alugados": 10,
    "data_inicio": "30/01/2003",
    "cliente_id": 1,
    "carro_id": 3
}

### Buscar Aluguel
GET http://localhost:8080/aluguel/buscar/10

### Listar Alugueis Ativos
GET http://localhost:8080/aluguel/listarAtivos

### Listar Alugueis Desativados
GET http://localhost:8080/aluguel/listarDesativados

### Listar Todos os Alugueis
GET http://localhost:8080/aluguel/listarTodos

### Editar Aluguel
POST http://localhost:8080/aluguel/editar/
Content-Type: application/json

{
    "data_inicio": "30/01/2003",
    "data_termino": "30/01/2003"
}

### Devolver/desativar Aluguel
DELETE http://localhost:8080/aluguel/desativar/2

### Ativar Aluguel
PATCH http://localhost:8080/aluguel/ativar/1

