### Cadastrar Carro
POST http://localhost:8080/carro/cadastrar
Content-Type: application/json

{
    "modelo": "Ford Ka",
    "valor_dia": 100.1,
    "unidades": 1
}

### Buscar Carro
GET http://localhost:8080/carro/buscar/1

### Listar Carros
GET http://localhost:8080/carro/listar

### Editar Carro
POST http://localhost:8080/carro/editar/
Content-Type: application/json

{
    "modelo": "Ford Ka",
    "valor_dia": 100.1,
    "unidades": 10
}

### Desativar Carro
DELETE http://localhost:8080/carro/desativar/1

### Ativar Carro
PATCH http://localhost:8080/carro/ativar/1