ALTER TABLE IF EXISTS ALUGUEIS
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE IF EXISTS ALUGUEIS
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE IF EXISTS ALUGUEIS
    ADD COLUMN created_by VARCHAR(100);

ALTER TABLE IF EXISTS ALUGUEIS
    ADD COLUMN aluguel_status text[];
