ALTER TABLE IF EXISTS CLIENTES
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE IF EXISTS CLIENTES
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE IF EXISTS CLIENTES
    ADD COLUMN created_by VARCHAR(100);
